### ISSUE TITLE
404 Usage docs link

### ISSUE THREAD

**Issue by ffirg** [ansible/ansible-rulebook#226]
### Description

bottom of https://ansible-rulebook.readthedocs.io/en/latest/readme.html just before Credits section Usage link points to usage.rst and should be https://ansible-rulebook.readthedocs.io/en/latest/usage.html

### What I Did
Clicked the link and got disappointed :(

**Comment by ffirg** [comment]
might want to check the whole docs for .rst refs as installation is affected too.

**Comment by ttuffin** [comment]
Thanks for the report @ffirg. This was resolved in #277 with the docs refactor.
