### ISSUE TITLE
could not find source plugin ansible.eda.range

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/ansible-rulebook#693]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/ansible-rulebook/issues) for duplicates.
- [X] I understand that ansible-rulebook is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Documentation for an ansible-rulebook content developer does not mention `ansible-galaxy collection install ansible.eda`, which is required to get the first example in the Rulebook working.

### Environment

```cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"
```

### Steps to reproduce

* Read and complete the Installation docs
* Read and complete the Usage docs
* Move onto the Rulebook docs and try the first example

### Actual results

```
ansible-rulebook --rulebook chaos.yml --inventory inventory.yml
2024-06-07 13:08:39,153 - ansible_rulebook.engine - ERROR - Source error Could not find source plugin for ansible.eda.range
2024-06-07 13:08:39,153 - ansible_rulebook.engine - ERROR - Shutting down source: ansible.eda.range error : Could not find source plugin for ansible.eda.range
2024-06-07 13:08:39,169 - ansible_rulebook.app - ERROR - Could not find source plugin for ansible.eda.range
2024-06-07 13:08:39,170 - ansible_rulebook.cli - ERROR - Terminating One of the source plugins failed
```

### Expected results

After completing the Installation -> Usage and moving on to the Rulebook section of the docs. I expect to be able to run the first example.

### Additional information

I had to install the `ansible.eda` collection via `ansible-galaxy collection install ansible.eda`. I didn't find this step in the Developer section, I just got lucky. Now I see it's in the Developer section but I'd argue it should be more front and center. Probably in the Installation section but I could see it in the Rulebook section too.

I wouldn't think to go to the Developer doc section because I figure that is for contributing to the `ansible-rulebook` project. I'm just looking to author content.

**Comment by Alex-Izquierdo** [comment]
Hello @chrismeyersfsu 
Thanks for your report. Technically, ansible.eda is not required to use ansible-rulebook, and I think we took that reasoning when writing the documentation. I agree that it might be a mistake if later we are referencing that collection in our examples. I think we should mention it.

**Comment by Alex-Izquierdo** [comment]
Sorry, @chrismeyersfsu reviewing the current documentation I have found that we already have a step to install the collection, in both places, the developer section and the general installation guide:
https://github.com/ansible/ansible-rulebook/blob/main/docs/installation.rst?plain=1#L40
https://github.com/ansible/ansible-rulebook/blob/main/docs/development_environment.rst?plain=1#L31

Where and how did you consult the documentation?

**Comment by chrismeyersfsu** [comment]
:facepalm: You are 100% correct. The installation docs say to install the `ansible.eda` collection. https://ansible.readthedocs.io/projects/rulebook/en/stable/installation.html#installation-via-pip

Closing this issue.
